const locations = [
  {
    id: 1,
    name: "Lieu 1",
    latitude: 48.8516666,
    longitude: 2.3132107,
    description: "C'est une description de l'emplacement 1.",
    imageSrc: "/photos/01.webp",
    linkUrl: "/locations/1",
    date: "15 Octobre 2023",
    tags: ["Nature", "ONF", "Enfants"],
  },
  {
    id: 2,
    name: "Lieu 2",
    latitude: 48.8628631,
    longitude: 2.4047319,
    description: "C'est une description de l'emplacement 2.",
    imageSrc: "/photos/02.webp",
    linkUrl: "/locations/2",
    date: "22 Octobre 2023",
    tags: ["Aventure", "Kinomé", "Famille"],
  },
  {
    id: 3,
    name: "Lieu 3",
    latitude: 44.8628631,
    longitude: 2.2047319,
    description: "C'est une description de l'emplacement 3.",
    imageSrc: "/photos/03.webp",
    linkUrl: "/locations/3",
    date: "29 Octobre 2023",
    tags: ["Art", "ONF", "Créativité"],
  },
  {
    id: 4,
    name: "Lieu 4",
    latitude: 43.8628631,
    longitude: 2.4047319,
    description: "C'est une description de l'emplacement 4.",
    imageSrc: "/photos/04.webp",
    linkUrl: "/locations/4",
    date: "5 Novembre 2023",
    tags: ["Science", "Kinomé", "Découverte"],
  },
  {
    id: 5,
    name: "Lieu 5",
    latitude: 48.8628631,
    longitude: 1.4047319,
    description: "C'est une description de l'emplacement 5.",
    imageSrc: "/photos/05.webp",
    linkUrl: "/locations/5",
    date: "12 Novembre 2023",
    tags: ["Histoire", "ONF", "Culture"],
  },
];

export default locations;
